### PR TITLE
Automatically package and release the plugin binary

### PR DESCRIPTION
**Pull request by diranged**
*Issue #, if available:*

N/A

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

This change uses Github actions to package up the plugin binary so that it can be downloaded directly from Github. This supports users who are running Fluentbit natively (via Debian or Redhat packages) but want to leverage these plugins.

### CODE REVIEW

**Comment by hossain-rayhan** [comment]
Hi @diranged , thanks for this contribution. 
Before diving deep, let's discuss something. I got two questions on my mind. 

1. When do we publish the binaries (on every push/ merged pull request)? I think we need some kind of mechanism to trigger the release on some specific pull requests.
2. I am not sure but I feel we need separate binaries for `arm64` and `amd64`?

**Comment by diranged** [comment]
> Hi @diranged , thanks for this contribution.
> Before diving deep, let's discuss something. I got two questions on my mind.
> 
> 1. When do we publish the binaries (on every push/ merged pull request)? I think we need some kind of mechanism to trigger the release on some specific pull requests.

This configuration will build and publish the binary any time you tag a release.

> 2. I am not sure but I feel we need separate binaries for `arm64` and `amd64`?
I definitely thought about that too ... but it seems like right now you are only building a docker image for amd64 anyways.. right?

I am happy to see arm64 and amd64 binaries built though, but that seems like it would require a bit more refactoring. Right?

**Comment by hossain-rayhan** [comment]
> I definitely thought about that too ... but it seems like right now you are only building a docker image for amd64 anyways.. right?

Not actually, we release docker images for both of `AMD64` and `ARM64`. You can check our last release.

**Review by PettitWesley — APPROVED** [review]
I am fine with this change... @hrayhan do you have any concerns?

**Comment by hossain-rayhan** [comment]
I am also OK with this contribution. The only thing I am not sure if we have any AWS security concerns here `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`. 

Another thing-- maybe we want to follow similar approch for other plugins as well.

**Comment by PettitWesley** [comment]
@hossain-rayhan Good point... I am not familiar with GitHub actions or where that bit comes from/what it means

And we possibly do need some sort of AWS Security approval for any new release process...

**Pull request closed without merging**
