### PR TITLE
Print the plugin version with name

### PR DESCRIPTION
**Pull request by hossain-rayhan**
*Description of changes:*
When the plugin is built, it prints the name. It might be cool if we print the version as well. It will help to be sure that we are building the correct version. 
If we agree on this, we can do the same for our other plugins. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by PettitWesley — APPROVED** [review]
@hossain-rayhan I like the idea

Bonus points: embed the version in the code and print it on startup when it runs.

The way you do this is to generate a go file when you build that includes the version; there are multiple ways to do that, ECS CLI does it with this:

**Comment by PettitWesley** [comment]
> Bonus points: embed the version in the code and print it on startup when it runs.

TBH, it would be cool, but we probably have higher priority things to do right now..

**Comment by hossain-rayhan** [comment]
> > Bonus points: embed the version in the code and print it on startup when it runs.
> 
> TBH, it would be cool, but we probably have higher priority things to do right now..

@PettitWesley I agree and prefer not to invest more time now.

**Comment by hencrice** [comment]
JFYI, we actually replaced the clunky version injection mechanism in ECS CLI with https://github.com/aws/copilot-cli/blob/master/Makefile#L17 in AWS Copilot to natively support compile time variable injection. More details can be found on: https://goenning.net/2017/01/25/adding-custom-data-go-binaries-compile-time/

**Comment by PettitWesley** [comment]
@hencrice Interesting- that's a lot better 👍

**Pull request merged**
